name = "Cobblemon Plus"
author = "Thecat8413"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f35baf4f0dbf424257c336ff48023e6a04bc1ceb493b80f23737f60236a03c1b"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.20.1"]
