name = "Cobblemon Plus"
author = "Thecat8413"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71ee3e29e0c3eb4c026e9b40bc7234feee071a205b01b976a5b46457cbe4d4a6"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.20.1"]
