name = "Cobblemon Plus"
author = "Thecat8413"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d6ad31910989e64df83c7d728c5e0cfda66e9f4f69eacf26d35e8330dc8aed6"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.20.1"]
